apiVersion: batch/v1
kind: CronJob
metadata:
  name: mongodb-backup
  namespace: miniproject
spec:
  schedule: "0 0 * * *" # Daily at midnight
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backup
              image: mini_project-backup:v2
              imagePullPolicy: IfNotPresent
              command: ["/backup.sh"]
              env:
                - name: MONGO_URI
                  valueFrom:
                    secretKeyRef:
                      name: mongodb-secret
                      key: MONGO_URI
                - name: MINIO_URL
                  value: "http://minio:9000"
                - name: MINIO_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: minio-secret
                      key: MINIO_ACCESS_KEY
                - name: MINIO_SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: minio-secret
                      key: MINIO_SECRET_KEY
          restartPolicy: OnFailure
