apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: miniproject
type: Opaque
stringData:
  JWT_PUBLIC_KEY: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyJ4NdxWixbfS27CgQrtsCoA/c09MK7iEklI08JJKCuEgT4Rmw+tWvOnjfA+unSk3348GhwLgyRPvap7YCoxFE5zJb92FTRYcAqkdKLwTPS+8usXDEBp6hK9F/t6967gqbcBLzFCwmuOfzqKa0CI9npdDiL3PaQ8cUJEX0f83oRn1B2MnK0uO+ZQl2Grjw4DrQS5215/tCwodaovbmvvUpaXqL+dNCJgEc6A1vqNFUzrsgkTS6X1O1Kuswa1lSxRfaMQHa2WEzCJeJ5swrbxYFh/Wrggh0vmGqIQR9RfBl17QBqBfoifvZHGUCuc+Zc0nwmYFvDO/+o9LyB/G8Au82QIDAQAB"
  KEYCLOAK_PUBLIC_KEY: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyJ4NdxWixbfS27CgQrtsCoA/c09MK7iEklI08JJKCuEgT4Rmw+tWvOnjfA+unSk3348GhwLgyRPvap7YCoxFE5zJb92FTRYcAqkdKLwTPS+8usXDEBp6hK9F/t6967gqbcBLzFCwmuOfzqKa0CI9npdDiL3PaQ8cUJEX0f83oRn1B2MnK0uO+ZQl2Grjw4DrQS5215/tCwodaovbmvvUpaXqL+dNCJgEc6A1vqNFUzrsgkTS6X1O1Kuswa1lSxRfaMQHa2WEzCJeJ5swrbxYFh/Wrggh0vmGqIQR9RfBl17QBqBfoifvZHGUCuc+Zc0nwmYFvDO/+o9LyB/G8Au82QIDAQAB"
  KEYCLOAK_URL: "http://keycloak:8080/auth"
  KEYCLOAK_REALM: "miniproject"
