apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: miniproject
type: Opaque
stringData:
  KC_DB_PASSWORD: "password"
  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "admin"
