apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: default
type: Opaque
stringData:
  MINIO_ROOT_USER: "rootuser"
  MINIO_ROOT_PASSWORD: "rootpassword123"
  MINIO_ACCESS_KEY: "rootuser"
  MINIO_SECRET_KEY: "rootpassword123"
