apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: default
type: Opaque
stringData:
  REDIS_URL: "redis://redis:6379"
  # REDIS_PASSWORD: "" # Uncomment and set if Redis auth is enabled
