apiVersion: apps/v1
kind: Deployment
metadata:
  name: research-service
  namespace: miniproject
  labels:
    app: research-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: research-service
  template:
    metadata:
      labels:
        app: research-service
    spec:
      containers:
        - name: research-service
          image: mini_project-research-service:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3007
          envFrom:
            - configMapRef:
                name: research-service-config
            - secretRef:
                name: mongodb-secret
            - secretRef:
                name: minio-secret
            - secretRef:
                name: jwt-secret
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 3007
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 3007
            initialDelaySeconds: 30
            periodSeconds: 15
            failureThreshold: 3
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
