apiVersion: v1
kind: Service
metadata:
  name: job-service
  namespace: miniproject
spec:
  selector:
    app: job-service
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
  type: ClusterIP
